[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = ["poetry install --no-root"]

[phases.build]
cmds = []

[start]
cmd = "poetry run uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
